# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "project"
BBFILE_PATTERN_project = "^${LAYERDIR}/"
BBFILE_PRIORITY_project = "6"

# Optional BSP layers that may optionally be present in bblayers.conf
BBFILES_DYNAMIC += " \
    intel:${LAYERDIR}/dynamic-layers/meta-intel/recipes-*/*/*.bb \
    intel:${LAYERDIR}/dynamic-layers/meta-intel/recipes-*/*/*.bbappend \
    tegra:${LAYERDIR}/dynamic-layers/meta-tegra/recipes-*/*/*.bb \
    tegra:${LAYERDIR}/dynamic-layers/meta-tegra/recipes-*/*/*.bbappend \
    raspberrypi:${LAYERDIR}/dynamic-layers/meta-raspberrypi/recipes-*/*/*.bb \
    raspberrypi:${LAYERDIR}/dynamic-layers/meta-raspberrypi/recipes-*/*/*.bbappend \
"

LAYERDEPENDS_project = "core openembedded-layer sota"

LAYERSERIES_COMPAT_project = "scarthgap"
